-- Flyway baseline schema for mapa-social
-- Executed after switching from Hibernate auto DDL to migrations.
-- If existing production data already exists, mark this as baseline with flyway -baselineOnMigrate=true.

-- ===================== TABLES =====================
CREATE TABLE categoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255)
);

CREATE TABLE endereco (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rua VARCHAR(100) NOT NULL,
    numero INTEGER NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf CHAR(2) NOT NULL,
    cep VARCHAR(9) NOT NULL,
    complemento VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);

CREATE TABLE usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    data_cadastro TIMESTAMP NOT NULL,
    bloqueado BOOLEAN NOT NULL
);

CREATE TABLE servico_social (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    telefone VARCHAR(20),
    endereco_id INTEGER NOT NULL,
    categoria_id INTEGER NOT NULL,
    CONSTRAINT fk_servico_endereco FOREIGN KEY (endereco_id) REFERENCES endereco(id) ON DELETE CASCADE,
    CONSTRAINT fk_servico_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON DELETE RESTRICT
);

CREATE TABLE solicitacoes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    servico_social_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    data_solicitacao TIMESTAMP NOT NULL,
    observacao VARCHAR(1000),
    data_resposta TIMESTAMP,
    resposta_admin VARCHAR(1000),
    CONSTRAINT fk_solicitacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    CONSTRAINT fk_solicitacao_servico FOREIGN KEY (servico_social_id) REFERENCES servico_social(id) ON DELETE CASCADE
);

CREATE TABLE favorito (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    servico_social_id INTEGER NOT NULL,
    data_inclusao TIMESTAMP NOT NULL,
    CONSTRAINT fk_favorito_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    CONSTRAINT fk_favorito_servico FOREIGN KEY (servico_social_id) REFERENCES servico_social(id) ON DELETE CASCADE
);

CREATE TABLE historico (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    servico_social_id INTEGER NOT NULL,
    data_acesso TIMESTAMP NOT NULL,
    CONSTRAINT fk_historico_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    CONSTRAINT fk_historico_servico FOREIGN KEY (servico_social_id) REFERENCES servico_social(id) ON DELETE CASCADE
);

CREATE TABLE sugestao_servico (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_sugerido VARCHAR(150) NOT NULL,
    endereco_sugerido VARCHAR(255),
    descricao_sugerida VARCHAR(500),
    status VARCHAR(50) NOT NULL,
    usuario_id INTEGER,
    data_sugestao TIMESTAMP NOT NULL,
    CONSTRAINT fk_sugestao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE SET NULL
);

-- ===================== INDEXES =====================
CREATE INDEX idx_servico_categoria ON servico_social(categoria_id);
CREATE INDEX idx_servico_endereco ON servico_social(endereco_id);
CREATE INDEX idx_solicitacao_usuario ON solicitacoes(usuario_id);
CREATE INDEX idx_solicitacao_servico ON solicitacoes(servico_social_id);
CREATE INDEX idx_favorito_usuario ON favorito(usuario_id);
CREATE INDEX idx_favorito_servico ON favorito(servico_social_id);
CREATE INDEX idx_historico_usuario ON historico(usuario_id);
CREATE INDEX idx_historico_servico ON historico(servico_social_id);
CREATE INDEX idx_sugestao_usuario ON sugestao_servico(usuario_id);

-- ===================== NOTES =====================
-- Seeding de dados (categorias, serviços) permanece via DataInitializer controlado para não duplicar.
-- Após aplicar esta migration, altere spring.jpa.hibernate.ddl-auto para 'validate'.
